//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 02:40:10 PM CET 
//


package fr.simplex_software.red_hat.fuse.osgi.standalone.customers.data.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="coorporateCustomers" type="{}coorporateCustomersType"/&gt;
 *         &lt;element name="individualCustomers" type="{}individualCustomersType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="internalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customersType", propOrder = {
    "coorporateCustomers",
    "individualCustomers"
})
public class CustomersType {

    @XmlElement(required = true)
    protected CoorporateCustomersType coorporateCustomers;
    @XmlElement(required = true)
    protected IndividualCustomersType individualCustomers;
    @XmlAttribute(name = "internalName", required = true)
    protected String internalName;

    /**
     * Gets the value of the coorporateCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link CoorporateCustomersType }
     *     
     */
    public CoorporateCustomersType getCoorporateCustomers() {
        return coorporateCustomers;
    }

    /**
     * Sets the value of the coorporateCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoorporateCustomersType }
     *     
     */
    public void setCoorporateCustomers(CoorporateCustomersType value) {
        this.coorporateCustomers = value;
    }

    /**
     * Gets the value of the individualCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualCustomersType }
     *     
     */
    public IndividualCustomersType getIndividualCustomers() {
        return individualCustomers;
    }

    /**
     * Sets the value of the individualCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualCustomersType }
     *     
     */
    public void setIndividualCustomers(IndividualCustomersType value) {
        this.individualCustomers = value;
    }

    /**
     * Gets the value of the internalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * Sets the value of the internalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalName(String value) {
        this.internalName = value;
    }

}
