//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 02:40:10 PM CET 
//


package fr.simplex_software.red_hat.fuse.osgi.standalone.customers.data.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.simplex_software.red_hat.fuse.osgi.standalone.customers.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Customers_QNAME = new QName("", "customers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.simplex_software.red_hat.fuse.osgi.standalone.customers.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomersType }
     * 
     */
    public CustomersType createCustomersType() {
        return new CustomersType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link ContactsType }
     * 
     */
    public ContactsType createContactsType() {
        return new ContactsType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link CoorporateCustomersType }
     * 
     */
    public CoorporateCustomersType createCoorporateCustomersType() {
        return new CoorporateCustomersType();
    }

    /**
     * Create an instance of {@link IndividualCustomersType }
     * 
     */
    public IndividualCustomersType createIndividualCustomersType() {
        return new IndividualCustomersType();
    }

    /**
     * Create an instance of {@link CoorporateCustomerType }
     * 
     */
    public CoorporateCustomerType createCoorporateCustomerType() {
        return new CoorporateCustomerType();
    }

    /**
     * Create an instance of {@link IndividualCustomerType }
     * 
     */
    public IndividualCustomerType createIndividualCustomerType() {
        return new IndividualCustomerType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomersType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomersType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "customers")
    public JAXBElement<CustomersType> createCustomers(CustomersType value) {
        return new JAXBElement<CustomersType>(_Customers_QNAME, CustomersType.class, null, value);
    }

}
